apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-secret
  
type: Opaque
data:
  QR_URL: "http://qr_python_code:8420/"
  MONGO_URI: "mongodb+srv://oachour08:MIBirKBLrN5MkfHW@qr-app-db.rmwfi3m.mongodb.net"
  MONGO_DB: "Qr-app-db"
  APP_PORT: "3000"
