deployment:
  frontend:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend-deployment
      labels:
        app: frontend
      namespace: training-app-frontend-prod
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: frontend
      template:
        metadata:
          labels:
            app: frontend
            app.kubernetes.io/name: frontend
        spec:
          containers:
          - name: frontend
            image: oussachour/qr_frontend:latest
            ports:
            - containerPort: 80
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
    
            volumeMounts:
                - name: configs
                  mountPath: /qr-frontend/assets/configs
          volumes:
            - name: configs
              configMap:
                name: website-configmap
  backend:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: backend-deployment
      labels:
        app: backend
      namespace: training-app-backend-prod
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: backend
      template:
        metadata:
          labels:
            app.kubernetes.io/name: backend
            app: backend
        spec:
          containers:
          - name: backend
            image: oussachour/qr_backend
            ports:
              - containerPort: 3000
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
            env:
              - name: APP_PORT
                valueFrom:
                  secretKeyRef:
                    name: mongo-db-secret
                    key: APP_PORT
              - name: QR_URL
                valueFrom:
                  secretKeyRef:
                    name: mongo-db-secret
                    key: QR_URL
              - name: MONGO_URI
                valueFrom:
                  secretKeyRef:
                    name: mongo-db-secret
                    key: MONGO_URI
              - name: MONGO_DB
                valueFrom:
                  secretKeyRef:
                    name: mongo-db-secret
                    key: MONGO_DB
  python:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: python-deployment
      labels:
        app: python
      namespace: training-app-backend-prod
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: python
      template:
        metadata:
          labels:
            app.kubernetes.io/name: python
            app: python
        spec:
          containers:
            - name: python
              image: oussachour/qr_python_code:latest
              ports:
                - containerPort: 8420
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"
              env:
                - name: QR_TMP_FOLDER
                  valueFrom:
                    secretKeyRef:
                      name: minio-s3-secret
                      key: QR_TMP_FOLDER
                - name: QR_FILL_COLOR
                  valueFrom:
                    secretKeyRef:
                      name: minio-s3-secret
                      key: QR_FILL_COLOR
                - name: QR_BACKGROUND_COLOR
                  valueFrom:
                    secretKeyRef:
                      name: minio-s3-secret
                      key: QR_BACKGROUND_COLOR
                - name: USE_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: minio-s3-secret
                      key: USE_BUCKET
                - name: BUCKET_ENDPOINT
                  valueFrom:
                    secretKeyRef:
                      name: minio-s3-secret
                      key: BUCKET_ENDPOINT
                - name: BUCKET_ENDPOINT_WEB
                  valueFrom:
                    secretKeyRef:
                      name: minio-s3-secret
                      key: BUCKET_ENDPOINT_WEB
                - name: BUCKET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-s3-secret
                      key: BUCKET_ACCESS_KEY
                - name: BUCKET_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-s3-secret
                      key: BUCKET_SECRET_KEY
                - name: BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: minio-s3-secret
                      key: BUCKET_NAME
                - name: BUCKET_PATH
                  valueFrom:
                    secretKeyRef:
                      name: minio-s3-secret
                      key: BUCKET_PATH  
ingress:
  frontend:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: ingress-frontend
      namespace: training-app-frontend-prod
    spec:
      rules:
        - host: "app.frontend.com"
          http:
            paths:
              - pathType: Prefix
                path: "/"
                backend:
                  service:
                    name: frontend-service
                    port:
                      number: 8080
      ingressClassName: nginx
  backend:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: ingress-backend
      namespace: training-app-backend-prod  
    spec:
      rules:
        - host: "app.backend.com"
          http:
            paths:
              - pathType: Prefix
                path: "/"
                backend:
                  service:
                    name: backend-service
                    port:
                      number: 3000
      ingressClassName: nginx
namespaces:
  frontend:
    apiVersion: v1
    kind: Namespace
    metadata:
      name: training-app-backend-prod
  backend:
    apiVersion: v1
    kind: Namespace
    metadata:
      name: training-app-frontend-prod
service:
  frontend:
    apiVersion: v1
    kind: Service
    metadata:
      name: frontend-service
      namespace: training-app-frontend-prod
    spec:
      selector:
        app.kubernetes.io/name: frontend
      type : LoadBalancer
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 80
  backend:
    apiVersion: v1
    kind: Service
    metadata:
      name: backend-service
      namespace: training-app-backend-prod
    spec:
      selector:
        app.kubernetes.io/name: backend
      type : LoadBalancer
      ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
  python:
    apiVersion: v1
    kind: Service
    metadata:
      name: python-service
      namespace: training-app-backend-prod
    spec:
      selector:
        app.kubernetes.io/name: python
      ports:
        - protocol: TCP
          port: 8420
          targetPort: 8420
configMaps:
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: website-configmap
    namespace: training-app-frontend-prod
  data:
    app_config.json: |-
      {
        "backendUrl": "http://app.backend.com:3000/access",
        "APP_PORT": "3000"
      }
sealedSecrets:
  minio_s3:
    apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      creationTimestamp: null
      name: minio-s3-secret
      namespace: training-app-backend-prod
    spec:
      encryptedData:
        BUCKET_ACCESS_KEY: AgB0XHJ5FUt5BC/BN1/lP9Ssnur589+s42SdYLNGaOP7EQpqIOpAanSX37+WoNHYhSfoVmv4G6YWBc51b6wLdmGcgMruwdByaDpOxSl1kjzP1esvYZ/lUizAd6x7d0e8Cwmjh+Ee4bS9eqXnWle0/Hn1LICEBmBuxlpSyGQE7uBeA9HwATD1E9dqZ1duo8zIk/sgBw2R20ayLc6keM1Q7rcQrbwDn8eg4m2nbglDCrKoETjd0lVnZ2diYdohve/JgqfsW5JY+9Z34SEoWpe+dXXHbDeURnY9b9WNJxMGgK3YiDZC/lv+sw0KqEQEOlEyFQKW0D52fladyfCJRGJVIY2VowZ13vOoSz1reRTm8tp9XS8dpUpEl3aX1OqZm5Eo0lZevIu7mh9ahA+/izadfRuc+9mqpmdDkAacU8FiDKP/XQAT96Cgkke97OoxRxqWqXehJ+LljC/0TysXvKY2Ejv2A2A+OQqAvmSEWd764MCnpYQPtEwcJrTTK+l3HzvKXVYQzpNtLqsY6GolU7cb2lLsZZaVRLqc/NvP7o8t4Ax/vUbOYrJbGFA4sevZW1DzFVmhhQ4R1bJAX1Ojk8q232HewM9BjUTdYfraBOSE7eBduh5kt1X8LYvsR90ZdUBo7ZUloFYl87diCEoTFLJoTlFIxceE5hfkK4KzF+MbC2TSfLs96Ol2yB3LLqAyQXuNRMs/oJyHguAugBo2ok2aWmNX/SfrQQ==
        BUCKET_ENDPOINT: AgAyyX8YwjEjYivO1rTHWvPNNqF2uATOMLleyhTHfNGsvD1TE9/IGokPd/t810yhmXqTRaRCdI7CgGn3bR3GfdMxhBVLOvfWK0pb55i5L8FNBWSH5JVpJm6EClfVmY2T2Fm5vpzbGYsAcm16EOa1gL7s2TMaUDOqA7mFT2onvIoEWeIdrsgPZhtp3CtE/Wcq2Pw0xNoIMVIkB71LLKtxy4nVDHoMLykqEf9ynAKL+xlUt47JIIJ0YkDle7igPSRFyhtZhuASkrZGP6NAuy3jEF5sWd6PN0//LOMGLMRfGzZPnBqPsZvQ0yF+JCOP8J4lPwlKlMFaTE6ObbRXbPrCGG48LZZm/wxt1qHnZmwBOE/TCYalRGna0fR2QDspGwuM9XXS7ni+XNb8JQUXeyEBV1rnumZdwrIduj0/DRIzDAtV8him763PMD/h+NlVbZN72v/i+n0Q87QAUqtUEvUzIKElvRpWxO2Ogu6hDtz2iduRCkheWVcBkKDzmTqhAGGIOfD2TuT9rjWU+ehjjBTBBgvbXaABXVnFAk92CPKx2TayWqORrpzTOfqYM6WDVo9zng4tfYMixTJCmMbMp2KpTDDDW0uGzYCPriddAMCPq28h8vap9L5SbbYFgawq42wLXc0Ro3Zpu8bMkbZfLnXbgmxDED1lN+SZED8pi/WJYa0OC4ybRvzaTOoCXW/zoffksH8L01bfiRYRyz7uZ6DgzzIY
        BUCKET_ENDPOINT_WEB: AgB4mT4pj2fv/wZtxxw93IbBNtzPYPjxFRl7s/6CrNUHLuRjYVLKki2J60ZKRE1TBOlg9hehflzDYOLf2ZK2p3yf3lhKI1t6PBDB1H0FkirNwe5AWJloBVUeveuFnRKcc2O/hhuY97wGKR3FFxQBjy1kXnaO6CfMmmtBqTW9vFXKy+SDVhLAgL/6d/lofpKzDV+bSY+TOXyDDGT1t9+prP0lBFZ2fZNglin9e9yURmyBgnL7A6Dvn9QuNw8vDtDSamg/JUP1VptaVh4rTnnxzTaNZN3af5zatfFiOtyga8ZUc/dHCt3Zezja66RmAzLsY6U9KDnq0Yk7AVTqvyQxHseoUwvq8955VIY0Fbc6krkKXSoi/TAJF0nmecUkrNHgKu8FR/VqH8AoydKwGrPi2jPMWy0rLbeh9tFwdpMHDwplsimdkz2NuSo6LTKxMOlzsL0Rqr4KMLKTi3kOdMRWr6mzncQrhwInKtKNR9r0Os5v4fR4wv+uJN4nYirIckPiG6peKhlXyIZfNjNpysOAui0rd+Nm1nlTX5E8qgQmmokN1VXsTWOxbjcq7Fe8gZCY9gQyLOOYRje7DJwIOZCJN24jkMRl+zOqBPAVWQXkuURcDGKlW0s1TBsnsuPCgjjWfFO2HJWWlA9kIyFVS2WzGFQrUR73R85Xy9/sNO+oOWNNQ7kYTOV4C2tzpXFwD/6Ty3Cl7uS4TEcYiz2G73i7ov7rXrC5G6Q8gA==
        BUCKET_NAME: AgB/D5BWMluinlmhNN2rOWlAag0bHyTMArWKu4kTaQWsHT5gUHjYsNqgSPiSfPbuXDJjdf0+LH7IKoBO3rTjZPfg8A30Lm/0HfqlD29X2rfP4G4wZqEbOa+gGj67Z9GZm1rzDQtqW44v+03QLvrWvjm2ndJy/1baIeKVG211C4MUp74sooOHMfC61vw85/5Qev+q/wcQq6aXK+067NL90EljCGnHpOj6ujrn6VyVUlMaZ6fI+5ICUsZz5RTlIpEowGUfGbniTdyRdiAj90zfDsWI9Wofs0CKDfJ1D+J9iz0ot9FTaM/MHcwNA9+IG3R59QTWudh3TlLkNabvx2/mzLgDaWfH5H95yIvywMRj1hA9lSUfXl8OdCCJN/fBmNU0dJvlDBaX+4PmnpVBEM3P5CK1Yt7az8wPANogc5X9/MfywUq5h/ENHT7mWi+hSmbR5v00GFPEAY6DiJvBoS9zFQYZqtq2CG30lZm3PM9q0Pfdl9MFr7pNbRKrGKCDY7onacXIWQiDaO1Ezn212G11q+hovn9S8CuDVK8UxWRtLsevJiLgZAXLLEtV6SKt4409buoEWsCcrGze0MoUkqeO+5GdDA5OC7OxiIY02VvfZ4QItL4xQATpFv+CHwPoVFRJ8haE7or+nOJ5gS+YBVSK1QPs98d+lOU5m7S60T+ZP/Cj5T/2glf+QLS1vi9sVj8jR21Ou03CU0KnA/XEg5I75Rw=
        BUCKET_PATH: AgCSrLzz6Hagf3vODrgxyNcLmemeFkML6bTNIlMqO0h5WvZbYZ41xuRYQUtupRIdrsnaPMDHQDeGi+339rlDSgQNIeBQ9k6sv3GQt0WyuFf0aa07bLOzrr3Qqa7OGOnXjbuZqHi7lsQ7ytBP/MiGS+NUIV5bdU7fYSKvJqbMZD0ieu8HLsysQujbh7WZPHIGhP3NnP8kCKdgB4J762u5ma7Gb0FlvgKqc3u8f03s1s3JNL4Uu0wQ800fsfPEhJpTqyMXsXanlt6pJa+uZ4027Avr/4mk9bltV4GbC2ejAEv1tHPJ0kHas7CWGcmKiK3L0JGBmNYc1taIcFsmq9AocHPfTXgKSC61n4vr/S71QT4Paj9ZdvRV513XF956CmqE2CSNeK5SK1aty7rc+71YdeRUd2TjRdcPRI9fODMQk5Jv3GRRlotBfS/XCiXUYELOia1xc7ILwIZvUDc8JJzCo+zBmWscI22Ju1Dfj4YHspHRwM44zqqYG2nj9Okq3XP92FylVRe9YF/2DYp2Lq2GvadfRmNjBLCKfmEjhfkmc5G9YQFRGTww4stmbOjuMj0u6CTzlPDpyFNyRrqkiwIrd31/Tt14qreOWwqQLHh/mm+fBGYSnRmvExFf7W+C1rtZlMkUj4DBgnPUGLbLSTMNKHMMSTGqCPIHCx+bzCSu5C8Cvzs8tSkup3PU8XAb04ZPnAg=
        BUCKET_SECRET_KEY: AgBNiA7/xduhfDjlhlmc6ndQI8P4zzrH7DGgBJy6g+FBBa1b/PJWJL1oLsMl5vXi7hPRaZFSvIRU0eY8eHrXlqaks/+nJEtdSFSwtxmTgaa0HWcIHNoMlA3xHbcalxbbY+DMjaR0ftndhw/37byJerFM1R8Rbg1gITvEWdLVktfatCd0tXU6vsxn8WYpZ1sgeWDTD/+L5FhvO8Lp63AfYu3ZWttZ443Di1Tu3defy6ndKrDjxftzx3QKNZuQx0jx3QlFiAwWYwSBX6QC//v58DU2lZjnY8Z7eDnJBJDpyn01S82J92QEX6HR2nneUDGZStrWT2ke5EAgPweqQT3CKtfLsd4t9GKzZA/9RbAs7Q5/2mHiOuDJONWWUZ+tDnCPhDA5VP9SqYdBsqaudTKroweYkzBngJu8Fwv0lvW+PSqX9smtrEoOtUxPyjotGdjCJDFeEriFxGCP1ui5Us/x02VgeUtaZkTZu+2WncXXqpR/21szCFZSjXiuJitebtBeXV9Ih7+vYM/ZLs7AT75DKRMEhAKEMk7cePuXytVZIsGE7jjiSWp5+3N0K6VRK46RzeLQPhmf+8C53hD5Y6yhHU1zKuqt0Cy7RUQ6Ol3Zhi5Mf8iH8RTnrnvj3TjfnSl/ziOwuWEwzfDtrOREXc9jXLjf37wOCAGpTpBk+SdImN0P5/eTvYfYG0bi0aNvA4xVQqAq13kFJsDywxYYhcgCSipCRYjMZBKHQge87x8wsoPeVJ6RsScFjOQy
        QR_BACKGROUND_COLOR: AgCZkLZyc+YVw5kFvOGuIZkm7rEJHKeeLw8EalB5hFrZzelE245eTIO/fVOFP/FBVYTo8FdaQqyYc6PszgUY8p9OybVmeL4LfJhOFQB2BwGyAEEv6UPCi0fBgoIMEZ8GO58kandedMVDZeZpmJLNYKr1oQqKc9UUDUhagwmdRL9hwFg//eXq5EY1tZj0TT3y9VTd44fYfRjFZQB7mgyszhNSNsbsxKKdKG3HWu+UBUyafoMFHmgWPCftMKr5W/86/GMGix46mKcAtNkQlByjVnBAXpSlk6qgX7QyBMMQJaFrPPEaZ1Gw/Ho9+m+mxvyfGtM6AVstoLC8fIIGiPqaEzXb6eWMlVyQ2nG3fQPiNx7jV+vaBxHJ9Jx3iBpFLCAxZoh9YddCGVXEivrKp8Ye8W3Yls9DUfi4IzQIgR2IfHjsleduqe/k2AQopI71bvltq2ClOZ2yqSLIcO/SocdwCt30encytWLLf96eRpCoSif5YDnam1vHmWHEQ9zbNtJx7OVVn+/fUseA47BnjE0OWoZfgV39ru+tObvKEMVBkbOWiMDzyhOSfslX9+F2FAZ2ax7tI+6IylLbnkdeLq6mOciDWYGZcb/PHwf8LVU4hN0pZpJelDZFby4w7kDHeOFJGZrlTPIYf9H4XFgVH0INtdb7qAPPdAtzVrrPdxJz/ikU40OtoKPZ3v910E4IgN87CH7jo9N9/IYa
        QR_FILL_COLOR: AgBKaoUVzS1WoMn6ywR2s9P6b31o9kQYpHOiKRKjMUo0TtoZ+qYu6Q5TnKIe1TUILwuntMGOlMCQbyus6RHlLE08rXD3DPMDWLCjhdEiqxCiTj06FzWWtVrCRr3unMc36Td/WZmcVsVjRkWSMgWGa03zxZtNwquGtcORo3+pX32f9T2xoUpGZbZu1R/t82OH5HJuoueMBaiVy9TfOGIe4VM2zyneTSLYN6IuRgxOeQhp45LMP0qKtyL6x77TNZ1ry6/M2VCdvBooEPk+xgGxvwK4mTYrfgsCFUj0I6aW+NFhih7HI03mAtdwKlS9Hx8xX+nOlAoyZCuQ/TdH2k/KCDwP224uEZEUgCM7q3n5DWF/giSdU4ZXEUQhYC/HWFDhkflZ7U1LnikxRQP3dRzuaoWVD8Nzz1fVWW6HlVJUXe4dk3mw39beTH2nqq11JLU6WPf8G5bRV4tpVaiv4d6ZpolXQkQePczVzLNavKC58e9A/xREvxEwMv47HESW+R/vYAePk2EZPeL1LmehN6dlt+ay46FTxrXbUN+C+LnWVy7l2sMFCg7ByeS1rK9Uf/pbb5NOHOuD/y0m8RaIwfYETJSbdkwc2ceEW0m5t3D6evV5U6QVmYJNqf6e7laN3JaqSbG1A9XRaX0cGJAVvvHbv8hyzDAg5NHail2K6FdzwLG3cwldBlI5gD4v/MlK9Pq7Fjx6rHsA6myb
        QR_TMP_FOLDER: AgAOuHd0cPrzVmXTadPw07oIUZG5TULrtOotlgbo8RBq4xaTzmdwfRAJrP13O9onpfMlG/ljnULzonHP3R/+Uxrx7ZvzjKMkSctUNQF3A/oGf/5kM7mkRQGaT9xndFN9sipkDurjj3b6VUCInDLKzLjDsNpvH1DoCvGoxyxY2PKhU3p/zNrAAdRwwfVQmRdyd3rSNgY0ZVEI/p6OxSRb8oAjIOwl1bYuHur46fu/HLBs2j5EqwW/v/zEIDavTQAoNXwoaPlyI1pjz7iTtwbmLvz6ZvjYlobODkQpXAbeBndhoj3pfGwBieHSICh+9m5KPFT/qL1RF2sWxALOlGtKk32kVgnP2FnIKXMott//bWnSG64UDqddmyKLr62/hcwaLz2CdcDbfsAJwZ1+1IcCVzDhVDatGf0GFUOISTcy2n5P8oMJIhKIP//8khbxY04ao1zm9MD/ULW1/h6JjkjOcYVqTwrvPhRUBX0aBIJOL1AHFZ2AJvVaKvWpt4kboio4EPm4mCl81LYJHSFQiN0YpUloVcv43zIk64jwXM53FvgUFu+h2n11RcDd1JpHQIAKOzK0TYz7m4WvJUvf62DBYTrHJfKqD/wR/nWOwqWm0CdqN8Qfo94f1Wj+XXm3dmm/IpE3jZ78mda8gWwVFsnjIdKfWVlPejjAfd8745Kda3aRNTkuYTHPtibiF9oqoovsgdCcpR0htB3zFNGNbLNGBQ==
        USE_BUCKET: AgB2YmzUuNXb3NaE6WO7MYb2f12LxDv9KMf4oN7F0yScJMAMSHOvHGjEXP+IeXmk/fH6eX1c2y8FkWh0rAGgEF5VYZEFWGuETEffyVUKWO2c0A8gZ7X9pH3OaTVu+xI4A1YSadoy09w04udkV07MA5QMkgRxBaxdZOPcWyOWhIURR0fUG8b7ImTD7uFoS1zVvhxxsTnvVq7FNio8/R+FihTUBplcvfCSYZbgd+ay6GK2CxBLTSLZDs1D3YezW/djgHh2UQLscVlUABh2iyPuebBaiZtXkcatHlNmerbXwCaAXOtd+i4ZaHXexh2dF1sVmJTAniSCmGEJCdh4IQrpQxbVdNq6qTjIh3281MCxu+PxdEIzSoX28lmJ/t2pgH/x4zifwIQQPjtnZFcYKt2Lr3B9TkCm9kzOWCGnpCgdraKkuLu7IHK1y3OyDMvmJhlaSbbuCZWCrBTpSI/xVJQtImqP/NxiGua//hxzgzfL1SKWGpwj/ZttlF/kctngtWbHbpVN7XPTRREd3a5+4PjzTfCCXZ7bmSDHxL7w1rEpepoYXPR4FvV1OAjJzPaqlxCRzC4/O4/rApCB3igkMz6UPNjiG/lnI5K7WMReM8takTP+OI0VYIdd6jdQ85c/ILYlQquzqvAy3fo/Xk4K08oTW/TdQd8+E8OpKRVJ+2wG7fzWK4GdpGBS9p+HFCnx/r6RDTKRz9Zh
      template:
        metadata:
          creationTimestamp: null
          name: minio-s3-secret
          namespace: training-app-backend-prod
        type: Opaque
  mongo_db:
    apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      creationTimestamp: null
      name: mongo-db-secret
      namespace: training-app-backend-prod
    spec:
      encryptedData:
        APP_PORT: AgBEfLWOyxKAZxIfciMOgK25oKPB3J8yMxJKaIk9Oy6mSfUSO5IBhvAxMke1Jf4WfGUfM6yQD7pwhR+GCrE0Z3NzTb7Tt8QdJzIhL7inocBoJ6cCkAaBoT7Zl1bIdrAc2EmA7BjbbA+x4DYCto9H0zjdCBa4ZRElrUkjbCkRRSbbtYxaxffKAd8nEPgJsvVv8RzEBX8TQAJL11HdFygg7FMTsOLDtmDLa2/g46u3Uuu/Yyap55r17Iko1FfaihNo3YCrhstFuysACwlBPNLWKIeYLbv70XXYb8G8nQtb8zRe4/qmI+Lco796FP7jsqqRwlDj7SWjU8VTyoMGhmsl8DDDRm5bYhb1BVVTPWkj+kcX/xLRRy72BSlaoNtQX5p7vk8u9Hjd0OQyOAz5PFk4JR3eAUoWrjcnBLt4P+U3Ln83vHaXK3P2u86cVfVy95K/lXG7TDnmIcY1JknShJcyZZtwhaZNCaJjgq2XRTOI+SwOyxUhUOkOylR4meypecag1ywN6jxS2vKchPueRxiQvcAK/LW2ker9TefS1FD5nHurgyUz0I4E/08zaBLT46ZCAxrw7gi2Qs3V9YzdHUu6CVXufkYnx4Pv4WAC1i9ji8d6ndtdGAOhIo2DFKI/UVKv7epePMggOEqnhcGx7EALmcpkOu2gVv/Sxtx18tBhxAhxeUjSRF/HckSXfJ67XLFfmheMKXWG
        MONGO_DB: AgB5k7UHoyIZFBZSqYTpkhvL4M6rOFrayXmzPPLxdxy8bDTjZolxvn3XakCdEHqKxu973koQi7r5q2CHDy83wI/1xMyUksdFmOzvxhA8mQF3cqerBEYFXO4plkKdwCJspjqhlpSbM8/tKgd6/pTNrBd416mGvbnOaHC1boJdWyWJVagYnj+78oPNfMiYhypRs8c3xTiLeJFli0v9BjL0v88GcsluAG1AzDBd5XVb/5Sp9SPDY/XoWnnsOnNeK0BnIom9pPWrQRqNRUnANaWL35uFA2s0WDr6x4e8g/9r8PcXbyZPuqhgwbW208EJIo8sAcFbu+da8BXJ885ICa85SHaeQqmH8EUxFOpCuKHWdLZqpNq9b7OjN5s4rQE3pATz8UH7+7R6QgwJQUS2wU3PI8Vr1WYDHXikTj+yT3xSENF2r9yMCmcLrHXION50eWUOAURRH+DC5/rmxnY44OSwN/o5nwxB8aM1LPQhpCv+hx9xelvzmfsIZ2Hl0ANpj3DavlZFswKvSqQ+tnurb2rxYEPRyD1Ra2HwdYj4XfsFWob5pLVAKzHMMPl4v96ZrXwgJzB90APLg3fxvddVWaVmysA/fC/Axw1X3attYL12M1iRVveugDZQQQ1xBQaGjMLNWzMGhCpHLjOFiKUiERpzWluDY4HkU5sPRSnsm4fd61WVk3UoqM/imXwSXhpyiK2LH4pLRxPuCzRjyMM=
        MONGO_URI: AgBn+Zhok7wEhdlyA8PO6jN57qVmHrHMK2yIQAUyVRy1dcXp0ltu3fdBRPwLL2sUD86iStHJJ1aNr0XxZvTL/QCKfzsbgs1anlywf3Y8lk489zgQE2QqF87tO1wfrcUa0aeVk1fklRNXPTkNl3Npp3buE3zuj42HWbU4oGDnU6yjMZVQqoVtrbjWbY/NxCkZq05cESBxc4sc8cLQXVkAxPozPEI44hl7usavWAOd6/WDWvIpWaB9l4HBKsL2bt/fmtWHdUUTowwGJA1amVblIVnWLxGjHSNhORPEUcWcth64a0ItL1XKy3kt93KTyLa6lW9hJs8RRFqrWESuTOM7duaxz3jvPva2PClItHKPYBWpGlvBJnc64kYvX3PwYJ3UFPJ0U4YAiTc0vu2yGcRY3UH5hYFmnQuY+wF4TCaPYn7w7MnDWZvUzRJ18N7fUKFJl6OkictzqRko/hriTnQT0ioUYcuUWsSBMpEGng0sNS20LPMwMlQET6cnkqsHMWC+1LTIUEtV9D2O6cHyx37NfO0Xxxf0pe7rMZw4+O4NP0753vkIgjUVrOMN7JoG2D6GyosZPo7zDFy7TV1oXhHfk1RwgTZ3ZYw27RWn4/giR4u4QjoB/qUQXUIfYMk/7Ld2c/YbB52DOxPbQHWZw9r7MIwf8qQaIvYw0U9C0vMZKB/BIn7o32yR9RcAmpQaYhyJvqyZY/kwBDN2FRpKZkm7PsC8kwT4vIlmz2qKwNvd4aFyBZJxJesIwBp6FpMM1Q3jejACga00qJ8Swo0ioWSvCz9DzWW8Ku1y
        QR_URL: AgBVs3+LH+BKBrf6mhGnZ8CnkP9HpvWaTN+OwIkks9+ioJSfkvxHyYH7WdWXbca/YIZr/d70eq4YkSXKVzj5eSoMSVhlJAwkJzVHaXzx2IcCYxyfZK7TI/o1Ng4BVnfVdCsmI9dtIWupbgHKTv28k+0HMDKCmlvPgNyHwy65+S4JeJFiw5DurMn0w9bj1jW20E4Am2qbG4FzMTNJAjOw1wIBu31ohnbvxFAKh4Z+nQtojB+Eme8DRYDuiFn5l2VFqO4pSrzNmdeX2XDiLdzzwxS1nHbRSyqqnqpiOjMoZTgNIB0Ltb+CWVf+rtDTJxurxQQo9/2J5YtivBoqxR7AHxOkfxbcA3wCCxzIPpneQDMPT7UAwtGQqmLNPNakJ4WJ9oUEpx37r6FK499by9m5gIj34g5KX5C7J9NBcxUe9XSlTj6amYwgt+2hi5UjVJf7EBCO7GlgnqB2MRY201h4Z8rlMQGaHmfa5Ekj7svVQFbU1wOO5xcaow26ZOxi3uu9DSosJXVGY9pgUhTL+woFZGkTaOId6IAPXrffGgZMNKMhZLcGZOpIFHG5cUpuhEHzoPHo34GfZSWMEWcVv3Zg7TD2QRyI0UofU+W6er2H4ihgQnY1jSKtxBtegmlL7I9Shzk3C8l6Wh9PQZeueS46iSG17UZtLTWxntonm3/EfVPnn1b58ECQ3ydkF+35Fk4zG3ptU39esIySYEYdOo383yZnJVKJ2gPset4//nM=
      template:
        metadata:
          creationTimestamp: null
          name: mongo-db-secret
          namespace: training-app-backend-prod
        type: Opaque


  