apiVersion: v1
kind: ConfigMap
metadata:
  name: website-configmap
  namespace: training-app-frontend-prod
data:
  #backendUrl: "http://localhost:3000/access"
  backendUrl: "app.backend.com"
  APP_PORT: "3000"
