apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
  namespace: training-app-frontend-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/name: frontend
    spec:
      containers:
      - name: frontend
        image: oussachour/qr_frontend:latest
        ports:
        - containerPort: 80
        # env: 
        # - name : backendUrl
        #   valueFrom:
        #     configMapKeyRef: 
        #       name: website-configmap
        #       key:  backendUrl
        # - name : APP_PORT
        #   valueFrom:
        #     configMapKeyRef: 
        #       name: website-configmap
        #       key:  APP_PORT  
        volumeMounts:
            - name: configs
              mountPath: /qr-frontend/assets/configs
      volumes:
        - name: configs
          configMap:
            name: website-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: training-app-frontend-prod
spec:
  selector:
    app.kubernetes.io/name: frontend
  type : LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80