apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
  namespace: training-app-backend-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python
        app: python
    spec:
      containers:
      - name: python
        image: oussachour/qr_python_code:latest
        ports:
        - containerPort: 8420
        #adding commands to troubleshoot
        # command: ["/bin/sh"]
        # args: ["-c", "while true; do sleep 10; done"]
        
        env:
        - name: QR_TMP_FOLDER
          valueFrom:
            secretKeyRef:
              name: minio-s3-secret
              key: QR_TMP_FOLDER
        - name: QR_FILL_COLOR
          valueFrom:
            secretKeyRef:
              name: minio-s3-secret
              key: QR_FILL_COLOR
        - name: QR_BACKGROUND_COLOR
          valueFrom:
            secretKeyRef:
              name: minio-s3-secret
              key: QR_BACKGROUND_COLOR
        - name: USE_BUCKET
          valueFrom:
            secretKeyRef:
              name: minio-s3-secret
              key: USE_BUCKET
        - name: BUCKET_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: minio-s3-secret
              key: BUCKET_ENDPOINT
        - name: BUCKET_ENDPOINT_WEB
          valueFrom:
            secretKeyRef:
              name: minio-s3-secret
              key: BUCKET_ENDPOINT_WEB
        - name: BUCKET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-s3-secret
              key: BUCKET_ACCESS_KEY
        - name: BUCKET_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-s3-secret
              key: BUCKET_SECRET_KEY
        - name: BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: minio-s3-secret
              key: BUCKET_NAME
        - name: BUCKET_PATH
          valueFrom:
            secretKeyRef:
              name: minio-s3-secret
              key: BUCKET_PATH  
--- 

apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: training-app-backend-prod
spec:
  selector:
    app.kubernetes.io/name: python
  ports:
    - protocol: TCP
      port: 8420
      targetPort: 8420