services:
    - name: docker:24.0.3-dind
      alias: dockerd

stages :
  - test
  - build
  - run

before_script:

  - ./ci-scripts/dockerhub-login.sh  

.build:
  stage: build
  image: docker:24.0.3-cli
  services:  
    - dockerd
  tags:
    - t-009-prod

build:
  extends: .build
  
  script: 
    - chmod u+x ./ci-scripts/build.sh 
    - ./ci-scripts/build.sh

