variables:
  CLUSTER_NAME: prod-qr-app
  TRIGGER_PIPELINE:  "false"
stages :
  - build
  - deploy


build:
  stage: build
  tags:
    - t-009-prod
  before_script:
    - ./ci-scripts/dockerhub-login.sh 
  script: 
    - chmod ugo+rwx ./ci-scripts/build.sh 
    - ./ci-scripts/build.sh
  only: 
    changes:
      - ./applications/backend/
      - ./applications/website/
      - ./applications/qr/
  
deploy :
  stage: deploy 
  rules: 
    - if: '$TRIGGER_PIPELINE == "true"'

  tags: 
    - t-009-prod
  before_script:
    - ./applications/kubernetes/init-k3d-cluster.sh $CLUSTER_NAME
    - chmod ugo+rwx ./applications/kubernetes/secrets/sealingSecrets.sh
    - ./applications/kubernetes/secrets/sealingSecrets.sh 
  script: 
    - chmod ugo+rwx ./applications/kubernetes/deploy.sh
    - ./applications/kubernetes/deploy.sh
      


