services:
    - name: docker:24.0.3-dind
      alias: dockerd

stages :
  - test
  - build
  - run

before_script:

  - ./ci-scripts/dockerhub-login.sh  

  

build:
  stage: build
  image: docker:latest
  services:  
    - docker:dind
  tags:
    - t-009-prod
  
  script: 
    - chmod ugo+rwx ./ci-scripts/build.sh 
    - ./ci-scripts/build.sh

