#services:
#    - name: docker:24.0.3-dind
#      alias: dockerd
#
stages :
  - test
  - build
  - deploy




#find-docker-port:
#  tags:
#    - t-009-prod
#  image: alpine
#  services:
#    - dockerd
#  script:
#    - apt-get update
#    - apt-get install nmap
#    - nmap -sT -p- docker
#
build:
  stage: build
#  image: docker:24.0.3-cli
#  services:  
#    - dockerd
  tags:
    - t-009-prod
  before_script:

    - ./ci-scripts/dockerhub-login.sh 
  script: 
    - chmod ugo+rwx ./ci-scripts/build.sh 
    - ./ci-scripts/build.sh
  only: 
    changes:
      - ./applications/backend/
      - ./applications/website/
      - ./applications/qr/
deploy :
  stage: deploy 
  tags: 
    - t-009-prod
  before_script:
    - ./applications/kubernetes/init-k3d-cluster.sh
    - chmod ugo+rwx ./applications/kubernetes/secrets/sealingSecrets.sh
    - ./applications/kubernetes/secrets/sealingSecrets.sh 
  script: 
    - chmod ugo+rwx ./applications/kubernetes/deploy.sh
    - ./applications/kubernetes/deploy.sh
      

