services:
    - name: docker:24.0.3-dind
      alias: dockerd

stages :
  - test
  - build
  - run

 

  
find-docker-port:
  tags:
    - t-009-prod
  image: alpine
  services:
    - dockerd
  script:
    - sudo apt-get update
    - sudo apt-get install nmap
    - nmap -sT -p- docker

build:
  stage: build
  image: docker:24.0.3-cli
  services:  
    - dockerd
  tags:
    - t-009-prod
  before_script:

    - ./ci-scripts/dockerhub-login.sh 
  script: 
    - chmod ugo+rwx ./ci-scripts/build.sh 
    - ./ci-scripts/build.sh

