apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-08-18T11:09:28Z"
  generateName: sealed-secrets-controller-687897dd6b-
  labels:
    name: sealed-secrets-controller
    pod-template-hash: 687897dd6b
  name: sealed-secrets-controller-687897dd6b-tg8vn
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: sealed-secrets-controller-687897dd6b
    uid: dc81f477-5118-4e98-acf8-b62152d2e3f8
  resourceVersion: "86960"
  uid: c935cec1-3d56-4489-a4a0-f6cc7d866a10
spec:
  containers:
  - command:
    - controller
    image: docker.io/bitnami/sealed-secrets-controller:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: sealed-secrets-controller
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1001
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-znwxk
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k3d-qr-app-agent-0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 65534
  serviceAccount: sealed-secrets-controller
  serviceAccountName: sealed-secrets-controller
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: tmp
  - name: kube-api-access-znwxk
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-08-18T11:09:28Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-08-22T07:22:11Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-08-22T07:22:11Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-08-18T11:09:28Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://b35b65f409717964a90e34deba8d0f2c2333e7de6fa89b35cd2f2b6327de80d4
    image: docker.io/bitnami/sealed-secrets-controller:latest
    imageID: docker.io/bitnami/sealed-secrets-controller@sha256:64080e7f9c6854ca9489349d6c9231fcb86104ffb45253888602c19539d8bab6
    lastState:
      terminated:
        containerID: containerd://1a6cdcfcee6369bda6ff93b75c61a134767ae35b09b8755207d7dd7fc336e0d5
        exitCode: 2
        finishedAt: "2023-08-22T07:21:48Z"
        reason: Error
        startedAt: "2023-08-22T07:21:48Z"
    name: sealed-secrets-controller
    ready: true
    restartCount: 14
    started: true
    state:
      running:
        startedAt: "2023-08-22T07:22:10Z"
  hostIP: 172.24.0.2
  phase: Running
  podIP: 10.42.0.191
  podIPs:
  - ip: 10.42.0.191
  qosClass: BestEffort
  startTime: "2023-08-18T11:09:28Z"
