version: '3'
services:
  qr_backend:
    image: oussachour/qr_backend:latest
    container_name: qr_backend
    restart: always
  
    networks:
      - qr_network
    ports: 
      - 3000:3000
    
   
    env_file:
      - .env


  qr_python_code:

    image: oussachour/qr_python_code:latest
    container_name: qr_python_code
    restart: always
 
    networks:
      - qr_network
    ports: 
      - 8420:8420
    volumes:
      - generated_qr:/usr/src/generated_qr:z
    env_file:
      - .env
    

  qr_front:
      image: oussachour/qr_frontend:latest
      container_name: qr_frontend
      restart: always
   
      networks:
        - qr_network
      ports: 
      - 80:80
      env_file:
      - .env
      volumes:
      - generated_qr:/qr-frontend/assets/data:ro    
networks:
  qr_network:
    driver: bridge

volumes:
  generated_qr: