version: '3'
services:
  qr_backend:
    container_name: qr_backend
    restart: always
    build: 
      context: backend
      dockerfile: Dockerfile  
    networks:
      - qr_app
    ports: 
      - 3000:3000
    depends_on:
      - qr_python_code
    env_file:
      - .env


  qr_python_code:
    container_name: qr_python_code
    restart: always
    build: 
      context: qr
      dockerfile: Dockerfile
    networks:
      - qr_app
    ports: 
      - 8420:8420
    volumes:
      - generated_qr:/usr/src/generated_qr
    env_file:
      - .env
    

  qr_front:
      container_name: qr_frontend
      restart: always
      build: 
        context: website
        dockerfile: Dockerfile
        target: front
      networks:
        - qr_app
      ports: 
      - 80:80
      env_file:
      - .env
      volumes:
      - generated_qr:/qr-frontend/assets/data:ro    
networks:
  qr_app:
    driver: bridge

volumes:
  generated_qr: