apiVersion: v1
kind: Secret
metadata:
  name: minio-s3-secret
  namespace: training-app-backend-prod
  
type: Opaque
data:
  QR_TMP_FOLDER: "Li9nZW5lcmF0ZWRfcXI="
  #new storage volume
  #QR_TMP_FOLDER: "./minio_data"

  BUCKET_ACCESS_KEY: "TW9IR2hUZFlQYllic0hiTndYSUw="
  BUCKET_SECRET_KEY: "ZlNjS01HSUdORHUyTlowYVFFb3lkVVFEcFpPaU5DcDhDWHFWQ0lvVA=="
  USE_BUCKET: "dHJ1ZQ=="
  
  BUCKET_NAME: "ZGV2b3BzLXRyYWluaW5n"
  BUCKET_ENDPOINT: "cGxheS5taW4uaW86OTQ0Mw=="
  BUCKET_ENDPOINT_WEB: "aHR0cHM6Ly9wbGF5Lm1pbi5pbzo5NDQzLw=="
  BUCKET_PATH: ""
  QR_FILL_COLOR: "IzEyMTEyOA=="
  QR_BACKGROUND_COLOR: "I2RjZGJkYg=="
  