deployment:
  frontend:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend-deployment
      labels:
        app: frontend
      namespace: training-app-frontend-prod
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: frontend
      template:
        metadata:
          labels:
            app: frontend
            app.kubernetes.io/name: frontend
        spec:
          containers:
          - name: frontend
            image: oussachour/qr_frontend:latest
            ports:
            - containerPort: 80
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
    
            volumeMounts:
                - name: configs
                  mountPath: /qr-frontend/assets/configs
          volumes:
            - name: configs
              configMap:
                name: website-configmap
  backend:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: backend-deployment
      labels:
        app: backend
      namespace: training-app-backend-prod
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: backend
      template:
        metadata:
          labels:
            app.kubernetes.io/name: backend
            app: backend
        spec:
          containers:
          - name: backend
            image: oussachour/qr_backend
            ports:
              - containerPort: 3000
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
            env:
              - name: APP_PORT
                valueFrom:
                  secretKeyRef:
                    name: mongo-db-secret
                    key: APP_PORT
              - name: QR_URL
                valueFrom:
                  secretKeyRef:
                    name: mongo-db-secret
                    key: QR_URL
              - name: MONGO_URI
                valueFrom:
                  secretKeyRef:
                    name: mongo-db-secret
                    key: MONGO_URI
              - name: MONGO_DB
                valueFrom:
                  secretKeyRef:
                    name: mongo-db-secret
                    key: MONGO_DB
  python:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: python-deployment
      labels:
        app: python
      namespace: training-app-backend-prod
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: python
      template:
        metadata:
          labels:
            app.kubernetes.io/name: python
            app: python
        spec:
          containers:
          - name: python
            image: oussachour/qr_python_code:latest
            ports:
            - containerPort: 8420
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
            env:
              - name: QR_TMP_FOLDER
                valueFrom:
                  secretKeyRef:
                    name: minio-s3-secret
                    key: QR_TMP_FOLDER
              - name: QR_FILL_COLOR
                valueFrom:
                  secretKeyRef:
                    name: minio-s3-secret
                    key: QR_FILL_COLOR
              - name: QR_BACKGROUND_COLOR
                valueFrom:
                  secretKeyRef:
                    name: minio-s3-secret
                    key: QR_BACKGROUND_COLOR
              - name: USE_BUCKET
                valueFrom:
                  secretKeyRef:
                    name: minio-s3-secret
                    key: USE_BUCKET
              - name: BUCKET_ENDPOINT
                valueFrom:
                  secretKeyRef:
                    name: minio-s3-secret
                    key: BUCKET_ENDPOINT
              - name: BUCKET_ENDPOINT_WEB
                valueFrom:
                  secretKeyRef:
                    name: minio-s3-secret
                    key: BUCKET_ENDPOINT_WEB
              - name: BUCKET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: minio-s3-secret
                    key: BUCKET_ACCESS_KEY
              - name: BUCKET_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: minio-s3-secret
                    key: BUCKET_SECRET_KEY
              - name: BUCKET_NAME
                valueFrom:
                  secretKeyRef:
                    name: minio-s3-secret
                    key: BUCKET_NAME
              - name: BUCKET_PATH
                valueFrom:
                  secretKeyRef:
                    name: minio-s3-secret
                    key: BUCKET_PATH  
  