frontend:
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: frontend-deployment
    labels:
      app: frontend
    namespace: training-app-frontend-prod
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: frontend
    template:
      metadata:
        labels:
          app: frontend
          app.kubernetes.io/name: frontend
      spec:
        containers:
        - name: frontend
          image: oussachour/qr_frontend:latest
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
  
          volumeMounts:
              - name: configs
                mountPath: /qr-frontend/assets/configs
        volumes:
          - name: configs
            configMap:
              name: website-configmap
  
  