frontend:
  apiVersion: v1
  kind: Service
  metadata:
    name: frontend-service
    namespace: training-app-frontend-prod
  spec:
    selector:
      app.kubernetes.io/name: frontend
    type : LoadBalancer
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 80