apiVersion: v1
kind: Secret
metadata:
  name: minio-s3-secret
  namespace: training-app-backend-prod
  
type: Opaque
data:
  QR_TMP_FOLDER: "Li9nZW5lcmF0ZWRfcXI="
  #new storage volume
  #QR_TMP_FOLDER: "./minio_data"
  #console login temporary credentials

  # MINIO_ACCESS_KEY: oussachour_minio
  # MINIO_SECRET_KEY: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  
  
  ### minio on local #### 
  # BUCKET_ENDPOINT: "MTkyLjE2OC4xLjg6OTAwMA=="
  # BUCKET_ENDPOINT_WEB: "aHR0cDovLzE5Mi4xNjguMS44OjkwMDA="
  # BUCKET_ACCESS_KEY: "d1h4OVVuNGwyTDQ0bDBOdEY2U3Q="
  # BUCKET_SECRET_KEY: "NmZFT0l5U3dPeVRBU2t3UHlxQlJjeUVKWTVncU0xT0tJdmdoaVlleA=="
  
  USE_BUCKET: "dHJ1ZQ=="
  
  BUCKET_NAME: "ZGV2b3BzLXRyYWluaW5n"
  BUCKET_PATH: ""
  QR_FILL_COLOR: "IzEyMTEyOA=="
  QR_BACKGROUND_COLOR: "I2RjZGJkYg=="
  
  ### minio in a k3d pod ### 

  
  #accessing minio service via IP @ 
  BUCKET_ENDPOINT: "MTcyLjI2LjAuMjo5MDAw"
  BUCKET_ENDPOINT_WEB: "aHR0cDovLzE3Mi4yNi4wLjI6OTAwMA=="  
  
  
  #accessing minio service via the host name 
  # !! python app not able to access the minio server  
  # BUCKET_ENDPOINT: "YXBwLm1pbmlvLmNvbTo5MDAw"
  # BUCKET_ENDPOINT: "aHR0cDovL2FwcC5taW5pby5jb206OTAwMA=="
    
  #accessing minio service via the service name 
  # BUCKET_ENDPOINT: "bWluaW8tc2VydmljZTo5MDAw"
  # BUCKET_ENDPOINT_WEB: "aHR0cDovL21pbmlvLXNlcnZpY2U6OTAwMA=="
  


  #fake access key
  #BUCKET_ACCESS_KEY: "ZmFsc2U="

  BUCKET_ACCESS_KEY: "YzlBTzdTRzFsMFFxMTN4ak5IS0U="
  BUCKET_SECRET_KEY: "eGdJY0h1SWhNRTdHb1cxcTJIbjQwQ2loYm5uVDhSY2V3SjdRN1FaZQ=="
  #TEST: $(echo -n "your-api-key" | base64 | tr -d '\n')
