apiVersion: {{.Values.deployment.backend.apiVersion}}
kind: {{.Values.deployment.backend.kind}}
metadata:
  name: {{.Values.deployment.backend.metadata.name}}
  labels:
    app: {{.Values.deployment.backend.metadata.labels.app}}
  namespace: {{.Values.deployment.backend.metadata.namespace}}
spec:
  replicas: {{.Values.deployment.backend.spec.replicas}}
  selector:
    matchLabels:
      app: {{.Values.deployment.backend.spec.selector.matchLabels.app}}
  template:
    metadata:
      labels:
        app: {{.Values.deployment.backend.spec.template.metadata.labels.app}}
        app.kubernetes.io/name: {{ index .Values "deployment" "backend" "spec" "template" "metadata" "labels" "app.kubernetes.io/name"}}

    spec:
      containers:
      {{- range $container := .Values.deployment.backend.spec.template.spec.containers}}
        - name: {{$container.name}}
          image: {{$container.image}}
          ports:
          {{- range $port := $container.ports}}
            - containerPort: {{$port.containerPort}}
          {{- end}}
          resources:
            requests:
              memory: {{$container.resources.requests.memory}}
              cpu: {{$container.resources.requests.cpu}}
            limits:
              memory: {{$container.resources.limits.memory}}
              cpu: {{$container.resources.limits.cpu}}
          env:
            {{- range $env := $container.env}}
            - name: {{$env.name}}
              valueFrom:
                secretKeyRef:
                  name: {{$env.valueFrom.secretKeyRef.name}}
                  key: {{$env.valueFrom.secretKeyRef.key}}
            {{- end }}
         
      {{- end }}
---

apiVersion: {{.Values.service.backend.apiVersion}}
kind: {{.Values.service.backend.kind}}
metadata:
  name: {{.Values.service.backend.metadata.name}}
  namespace: {{.Values.service.backend.metadata.namespace}}
spec:
  selector:
    app.kubernetes.io/name: {{ index .Values "service" "backend" "spec" "selector" "app.kubernetes.io/name" }}
  type : {{.Values.service.backend.spec.type}}
  ports:
    {{- range $port := .Values.service.backend.spec.ports }}
    - protocol: {{$port.protocol}}
      port: {{$port.port}}
      targetPort: {{$port.targetPort}}
    {{- end}}