apiVersion: {{.Values.deployment.backend.apiVersion}}
kind: {{.Values.deployment.backend.kind}}
metadata:
  name: {{.Values.deployment.backend.metadata.name}}
  labels:
    app: {{.Values.deployment.backend.metadata.labels}}
  namespace: {{.Values.deployment.backend.metadata.namespace}}
spec:
  replicas: {{.Values.deployment.backend.spec.replicas}}
  selector:
    matchLabels:
      app: {{.Values.deployment.backend.spec.selector.matchLabels.app}}
  template:
    metadata:
      labels:
        app: {{.Values.deployment.backend.spec.template.metadata.labels.app}}
        app.kubernetes.io/name: {{ index .Values "deployment" "backend" "spec" "template" "metadata" "labels" "app.kubernetes.io/name"}}

    spec:
      containers:
      - name: {{.Values.deployment.backend.spec.template.spec.containers.name}}
        image: {{.Values.deployment.backend.spec.template.spec.containers.image}}
        ports:
        - containerPort: {{.Values.deployment.backend.spec.template.spec.containers.containerPort}}
        resources:
          requests:
            memory: {{.Values.deployment.backend.spec.template.spec.containers.resources.requests.memory}}
            cpu: {{.Values.deployment.backend.spec.template.spec.containers.resources.requests.cpu}}
          limits:
            memory: {{.Values.deployment.backend.spec.template.spec.containers.resources.limits.memory}}
            cpu: {{.Values.deployment.backend.spec.template.spec.containers.resources.limits.cpu}}
        env:
          {{- range $env := .Values.deployment.backend.spec.template.spec.env}}
          - name: {{$env.name}}
            valueFrom:
              secretKeyRef:
                name: {{$env.valueFrom.secretKeyRef.name}}
                key: {{$env.valueFrom.secretKeyRef.key}}
          {{- end }}
---

apiVersion: {{.Values.service.backend.apiVersion}}
kind: {{.Values.service.backend.kind}}
metadata:
  name: {{.Values.service.backend.metadata.name}}
  namespace: {{.Values.service.backend.metadata.name}}
spec:
  selector:
    app.kubernetes.io/name: {{ index .Values "service" "backend" "spec" "selector" "app.kubernetes.io/name" }}
  type : {{.Values.service.backend.spec.type}}
  ports:
    - protocol: {{.Values.service.backend.spec.ports.protocol}}
      port: {{.Values.service.backend.spec.ports.port}}
      targetPort: {{.Values.service.backend.spec.ports.targetPort}}