apiVersion: {{.Values.ingress.backend.apiVersion}}
kind: {{.Values.ingress.backend.kind}}
metadata:
  name: {{.Values.ingress.backend.metadata.name}}
  namespace: {{.Values.ingress.backend.metadata.namespace}}
  
spec:
  rules:
  - host: {{.Values.ingress.backend.spec.rules.host}}
    http:
      paths:
      - pathType: {{.Values.ingress.backend.spec.rules.host.http.paths.pathType}}
        path: {{.Values.ingress.backend.spec.rules.host.http.paths.pathType.path}}
        backend:
          service:
            name: {{.Values.ingress.backend.spec.rules.host.http.paths.pathType.backend.service.name}}
            port:
              number: {{.Values.ingress.backend.spec.rules.host.http.paths.pathType.backend.service.port.number}}
  ingressClassName: {{.Values.ingress.backend.spec.rules.host.ingressClassName}}