apiVersion: {{.Values.ingress.backend.apiVersion}}
kind: {{.Values.ingress.backend.kind}}
metadata:
  name: {{.Values.ingress.backend.metadata.name}}
  namespace: {{.Values.ingress.backend.metadata.namespace}}
  
spec:
  rules:
  {{- range $rule :=.Values.ingress.backend.spec.rules }}
    - host: {{$rule.host}}
      http:
        paths:
        {{- range $path := $rule.http.paths }}
          - pathType: {{$path.pathType}}
            path: {{$path.path}}
            backend:
              service:
                name: {{$path.backend.service.name}}
                port:
                  number: {{$path.backend.service.port.number}}
        {{- end}}
  {{- end }}
  ingressClassName: {{.Values.ingress.backend.spec.ingressClassName}}