apiVersion: {{.Values.deployment.frontend.apiVersion}}
kind: {{.Values.deployment.frontend.kind}}
metadata:
  name: {{.Values.deployment.frontend.metadata.name}}
  labels:
    app: {{.Values.deployment.frontend.metadata.labels}}
  namespace: {{.Values.deployment.frontend.metadata.namespace}}
spec:
  replicas: {{.Values.deployment.frontend.spec.replicas}}
  selector:
    matchLabels:
      app: {{.Values.deployment.frontend.spec.selector.matchLabels.app}}
  template:
    metadata:
      labels:
        app: {{.Values.deployment.frontend.spec.template.metadata.labels.app}}
        app.kubernetes.io/name: {{ index .Values "deployment" "frontend" "spec" "template" "metadata" "labels" "app.kubernetes.io/name"}}

    spec:
      containers:
      - name: {{.Values.deployment.frontend.spec.template.spec.containers.name}}
        image: {{.Values.deployment.frontend.spec.template.spec.containers.image}}
        ports:
        - containerPort: {{.Values.deployment.frontend.spec.template.spec.containers.containerPort}}
        resources:
          requests:
            memory: {{.Values.deployment.frontend.spec.template.spec.containers.resources.requests.memory}}
            cpu: {{.Values.deployment.frontend.spec.template.spec.containers.resources.requests.cpu}}
          limits:
            memory: {{.Values.deployment.frontend.spec.template.spec.containers.resources.limits.memory}}
            cpu: {{.Values.deployment.frontend.spec.template.spec.containers.resources.limits.cpu}}
        volumeMounts:
            - name: {{.Values.deployment.frontend.spec.template.spec.volumeMounts.name}}
              mountPath: {{.Values.deployment.frontend.spec.template.spec.volumeMounts.mountPath}}
      volumes:
        - name: {{.Values.deployment.frontend.spec.template.spec.volumes.name}}
          configMap:
            name: {{.Values.deployment.frontend.spec.template.spec.volumes.configMap.name}}

---

apiVersion: {{.Values.service.frontend.apiVersion}}
kind: {{.Values.service.frontend.kind}}
metadata:
  name: {{.Values.service.frontend.metadata.name}}
  namespace: {{.Values.service.frontend.metadata.name}}
spec:
  selector:
    app.kubernetes.io/name: {{ index .Values "service" "frontend" "spec" "selector" "app.kubernetes.io/name" }}
  type : {{.Values.service.frontend.spec.type}}
  ports:
    - protocol: {{.Values.service.frontend.spec.ports.protocol}}
      port: {{.Values.service.frontend.spec.ports.port}}
      targetPort: {{.Values.service.frontend.spec.ports.targetPort}}