apiVersion: {{.Values.sealedSecrets.minio_s3.apiVersion}}
kind: {{.Values.sealedSecrets.minio_s3.kind}}
metadata:
  creationTimestamp: {{.Values.sealedSecrets.minio_s3.metadata.creationTimestamp}}
  name: {{.Values.sealedSecrets.minio_s3.metadata.name}}
  namespace: {{.Values.sealedSecrets.minio_s3.metadata.namespace}}
spec:
  encryptedData:
    {{- range $key,$value := .Values.sealedSecrets.minio_s3.spec.encryptedData}}
    {{$key}}: {{$value}}
    {{- end}}
  template:
    metadata:
      creationTimestamp: {{.Values.sealedSecrets.minio_s3.spec.template.metadata.creationTimestamp}}
      name: {{.Values.sealedSecrets.minio_s3.spec.template.metadata.name}}
      namespace: {{.Values.sealedSecrets.minio_s3.spec.template.metadata.namespace}}
    type: {{.Values.sealedSecrets.minio_s3.spec.template.type}}
